#ifndef CWS_ERRORS_H
 #define CWS_ERRORS_H

typedef enum cws_external_internal_soap_err_e {
  CWS_ERR_NULL_CONFIG=10,
  CWS_ERR_INIT_GSOAP,
  CWS_ERR_INIT_INTERNAL_GSOAP,
  CWS_ERR_INTERNAL_GSOAP_SERVE,
  CWS_ERR_INTERNAL_GSOAP_SUBCODE,
  CWS_ERR_INTERNAL_GSOAP_FAULTSTRING
} CWS_EXTERNAL_INTERNAL_SOAP_ERR;

#define SERVER_FAULT_OUT_OF_MEMORY_ERROR (int)(-7000)
#define SERVER_FAULT_OUT_OF_MEMORY_ERROR_MESSAGE "Out of memory"

#define SERVER_EMPTY_XML_OR_NULL_ERROR (int)(-7001)
#define SERVER_EMPTY_XML_OR_NULL_ERROR_MESSSAGE "Empty XML object or inexistent object"

#endif
